services:
  backend:
    build:
      context: nautilux_backend
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: postgres:14.12
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  frontend:
    build:
      context: nautilux_frontend
    ports:
      - "8001:8001"
    depends_on:
      - backend

volumes:
  postgres_data:
